name: Update M3U

on:
  schedule:
    - cron: "*/10 * * * *"   # Her 10 dakikada bir çalışır
  workflow_dispatch:          # Manuel çalıştırma için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Gerekli paketleri yükle
        run: pip install requests

      - name: Scripti çalıştır
        run: python ontvizle.py

      - name: M3U dosyasını push et
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add DeaTHLesS-sports.m3u
          git commit -m "Otomatik M3U güncellemesi"
          git push
